create table bookmark (
  bm_id integer primary key generated by default as identity,
  bm_title text not null,
  bm_url text not null,
  bm_description text,
  bm_rating smallint not null check(
    bm_rating >= 0
    and bm_rating <= 5
  )
);